### PR TITLE
Use variables for development database host/port

### PR DESCRIPTION
**Pull request by kevintraver**
Allow postgres development database host/port to be set.

### CODE REVIEW

**Comment by kevintraver** [comment]
Is there a way to entirely ignore the port setup if it is not specified? I assume it should probably stay a socket path if unchanged?

**Comment by tute** [comment]
Why do you need this? Does setting `DATABASE_URL` work in development?

**Comment by kevintraver** [comment]
A use case would be using Docker. Currently you must have a local instance of Postgres running when generating a new app.

**Comment by pedrosmmoreira** [comment]
@kevintraver @tute Just adding my two cents here: Suspenders does make some assumptions, namely of being used in a machine setup with the thoughtbot laptop script. I think the concern regarding Docker is valid, but it would have to be addressed in a wider scope.

I've been going back and forth on the idea of translating Laptop, Dotfiles and Suspenders to a Docker environment for some time, would be happy to collaborate on that :)

**Comment by tute** [comment]
> I've been going back and forth on the idea of translating Laptop, Dotfiles and Suspenders to a Docker environment for some time, would be happy to collaborate on that :)

I believe @jferris has been thinking about this too. I am interested in this project as well.

> @kevintraver @tute Just adding my two cents here: Suspenders does make some assumptions, namely of being used in a machine setup with the thoughtbot laptop script. I think the concern regarding Docker is valid, but it would have to be addressed in a wider scope.

I agree with this. `DATABASE_URL` should be enough, it's what Heroku uses, and so I will close this PR for now.

Thanks for your help!

**Pull request closed without merging**
