### PR TITLE
Move refills to the development group

### PR DESCRIPTION
**Pull request by derekprior**
Refills is not a runtime dependency. The gem is used strictly as a
generator in development mode. It's memory footprint is not
insignificant, so not loading in production will give us more headroom
on Heroku.

### CODE REVIEW

**Comment by gabebw** [comment]
:+1:

**Comment by tute** [comment]
:+1:

**Comment by derekprior** [comment]
According to derailed, this saves 18MB. That's a good deal of memory across 3 processes.

**Comment by mcmire** [comment]
Nice!

**Pull request merged**
