### PR TITLE
Use a gemset based on the app_name

### PR DESCRIPTION
**Pull request by toobulkeh**
I believe this requires rvm, but it might be a worthwhile addition for users with many projects in the same environment. I'm interested in your thoughts.

### CODE REVIEW

**Comment by tute** [comment]
Hi @toobulkeh, thanks for your contributions!

I never used myself gemsets. Do they protect us against potential problems? Why are they better than sharing libraries across applications?

Thanks!

**Comment by toobulkeh** [comment]
https://rvm.io/gemsets/basics

Gemsets and Bundler are relatively redundant, but I've seen a few cases where we use gems that aren't managed by the Gemfile (like Foreman was) and have a need to manage specific versions separate between projects.

**Comment by gylaz** [comment]
With `rbenv` I haven't had a need for gemsets in years.

**Comment by tute** [comment]
> With `rbenv` I haven't had a need for gemsets in years.

Is this because of something specific to `rbenv`? If so, what?

**Comment by zamith** [comment]
I don't use gemsets anymore as well, other than having to use `bundle exec` more often I haven't had any issues. But I'm interested in knowing what kind of issues could occur.

**Comment by gylaz** [comment]
> Is this because of something specific to rbenv? If so, what?

Yes -- it doesn't support gemsets. I haven't missed them.

**Comment by tute** [comment]
@toobulkeh given suspenders doesn't use foreman anymore, do you still see any benefit on adding this?

**Comment by toobulkeh** [comment]
Foreman was just an example. I believe I've had it happen on other gems before. If it comes up again, I'll add an example here.

**Pull request closed without merging**
