### PR TITLE
Finish .sample.env migration

### PR DESCRIPTION
**Pull request by mike-burns**
In a056e1a85398e7140ce60b7c14721f9149cfa2b6 we migrated from `.env` to
`.sample.env`. Some stray `.env` files were left behind; fix those.

### CODE REVIEW

**Comment by mike-burns** [comment]
Yup, this is why CI is failing.

**Comment by mike-burns** [comment]
Fixing this is now at the bottom of my to-do stack (at the top was #1022, but now that's fixed). Very clearly something in the test run is depending on that `.env` file existing.

**Comment by composerinteralia** [comment]
I think I know why this is failing. With this change the `ProfilerGenerator` now creates the `.sample.env`. `RunnerGenerator` (which comes after `ProfileGenerator`) then gets hung up waiting for confirmation whether to overwrite the existing `.sample.env`.

Perhaps running the `RunnerGenerator` before the `ProfilerGenerator` will fix this.

**Comment by mike-burns** [comment]
Is there a flag we can pass when we run the tests that is like the "always overwrite" flag?

**Comment by composerinteralia** [comment]
We could run generators with a `--force` or `--skip` flag, but that might hide real issues. In this case the ordering of the generators didn't really make sense, and the test failures helped us fix that. What I would like is a way to run the generators and fail if there are any conflicting files, but that option doesn't seem to exist.

**Comment by mike-burns** [comment]
Yeah makes sense. LGTM.

**Pull request merged**
