### PR TITLE
Updates version to 1.37.0

### PR DESCRIPTION
**Pull request by lorentrogers**
Updates News.md

[ci skip]

### CODE REVIEW

**Comment by tute** [comment]
Thank you, @lorentrogers! This looks great.

I'd add a comment for "Set development delivery_method to :file" with a bit more context, to let developers know that they can see their outbound emails from Rails in `tmp/mails`. They might find it useful.

With that, we'll merge and release. Thank you!

**Comment by tute** [comment]
Something like:

```
* Set development `action_mailer.delivery_method` to `:file`
  so that mails are copied to `./tmp/mails/` directory for easy development
  access.
```

**Comment by lorentrogers** [comment]
Updated!

**Comment by tute** [comment]
Thank you very much!

**Pull request merged**
