### PR TITLE
Bump Rails

### PR DESCRIPTION
**Pull request by purinkle**
* Release notes http://weblog.rubyonrails.org/2017/8/3/Rails-5-1-3-released/

### CODE REVIEW

**Comment by croaky** [comment]
I'm thinking we get this merged and then cut a new Suspenders release?

**Comment by purinkle** [comment]
@croaky, that was my plan for the next investment day.

**Comment by croaky** [comment]
Okay if I merge this in @purinkle? Thinking it would be cool to get a Suspenders release in before tomorrow's newsletter goes out.

**Comment by purinkle** [comment]
@croaky, yeah, go for it! 🚢

**Comment by croaky** [comment]
Merged in https://github.com/thoughtbot/suspenders/commit/3d05385d0157092e8bc63257f8df50deb3f04e62

**Pull request closed without merging**
