### PR TITLE
Update Bourbon to v5.0.0.beta.3

### PR DESCRIPTION
**Pull request by tysongach**

### CODE REVIEW

**Comment by tute** [comment]
If there are no changes to make in our markup or partials, LGTM. :+1:

**Comment by tysongach** [comment]
This should wait until https://github.com/thoughtbot/bitters/pull/222 gets merged and released.

**Comment by tute** [comment]
ping @tysongach! :)

**Comment by tysongach** [comment]
@tute We got the Bourbon 5 update merged into Bitters, we just need to cut a release over there. That should happen this week.

**Comment by tysongach** [comment]
@tute Updated! We released a Bitters update for Bourbon 5 support, which is now also in this PR.

**Comment by tute** [comment]
Cool. Should we release v5 (non-beta) before merging this in?

**Comment by tysongach** [comment]
@tute The code is in a really good place and we’re already using it on a few project, including the new thoughtbot.com, in Hub and a handful of client projects. I’d to merge to get people using it now, instead of having to swap out v4.

**Comment by tute** [comment]
I trust you that this is ready for merge, but then, isn't bourbon ready for a full release? Or are we blocked on something there?

**Comment by tysongach** [comment]
@tute The new documentation website is the last piece of the puzzle, which I’m working on now.

**Pull request merged**
