### PR TITLE
Mention coaching

### PR DESCRIPTION
**Pull request by jferris**

### CODE REVIEW

**Comment by calebthompson** [comment]
LGTM

**Comment by tute** [comment]
"We can help you set up a new Rails application, write your first feature, and get up and running on Heroku" sounds more for starters than for intermediate/advanced people that coaches prefer to work with.

Also, I'd put it after "Contributing" section, like in Clearance.

**Comment by tute** [comment]
Suggestion: I'd mention concrete problems, like authentication and authorization, mention our other gems, talk about software design.

**Comment by jferris** [comment]
> Suggestion: I'd mention concrete problems, like authentication and authorization, mention our other gems, talk about software design.

I've been trying to mention problems that people will likely have while using a specific project. If somebody needs help with Suspenders, I'm guessing that means they need help setting up a new project.

I think I'm happy with the current suggested problems, but I encourage you to write up an alternate paragraph and submit a pull request to revise.

**Pull request merged**
