### PR TITLE
Correctly indent config.static_cache_control line

### PR DESCRIPTION
**Pull request by gabebw**
Before:

  config.serve_static_files = ENV['RAILS_SERVE_STATIC_FILES'].present? 
config.static_cache_control = "public, max-age=#{1.year.to_i}"

After:

  config.serve_static_files = ENV['RAILS_SERVE_STATIC_FILES'].present?
 config.static_cache_control = "public, max-age=#{1.year.to_i}"

### CODE REVIEW

**Comment by croaky** [comment]
Good to merge.

**Comment by gabebw** [comment]
@croaky How do I test that this actually does what I'm 85% sure it will do? Do I have to do `rake install` and generate a new Rails app? Can I write a test?

**Comment by croaky** [comment]
I don't think this is worth a test for what it does and for the time needed in the setup phase of the feature specs.

**Comment by gabebw** [comment]
Makes sense.

**Comment by croaky** [comment]
Your time is too valuable to the world to write a spec for an instance of two-space indentation, Mr. Gabe Berke-Williams. Helping give that time back to humanity and its flora and fauna is my greatest achievement today.

**Pull request merged**
