### PR TITLE
Update Rails to 5.1

### PR DESCRIPTION
**Pull request by delphaber**
Update Rails to 5.1

(adds support for webpack too)

### CODE REVIEW

**Comment by delphaber** [comment]
Ouch... hound is barking out loud!

**Comment by delphaber** [comment]
I didn't change `config/puma.rb`, but I noticed that in Rails 5.1 they changed it a little (see railsdiff http://railsdiff.org/5.0.4/5.1.1 ).

Heroku guide on puma (https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server) has not been updated since 2016 though.

So I don't know if `config/puma.rb` needs an update, because I'm not a big expert of puma on heroku :D. Any idea?

**Comment by tute** [comment]
The puma diff has only comment changes, should be fine as is.

cc @nickcharlton for review, please! Thank you.

**Comment by delphaber** [comment]
I noticed that rails 5.1 now:

`Initialize Git repo when generating new app, if option --skip-git is not provided. (Pull Request)`

So I think I can remove the `init_git` step in suspenders. Will work on it this evening (CEST time)

**Comment by delphaber** [comment]
Ok I did it. The git repository is now created by Rails. `--skip-git` still exists in Rails.

**Comment by delphaber** [comment]
Have you changed hound settings? :D I'm pretty sure I had to use double quotes for strings before!

**Comment by nickcharlton** [comment]
@delphaber I _think_ that the organisation config got lost on Hound and had to be reset. If you pushed again it'll rerun and be happy.

**Comment by delphaber** [comment]
@nickcharlton I pushed an empty commit, but those hound comments did not disappear from the PR. I think we can ignore them anyway, since hound check is ok!

**Comment by nickcharlton** [comment]
@delphaber Thanks! I went through, confirmed by eye and then deleted the invalid comments.

Going to merge now!

**Pull request merged**
