### PR TITLE
Removes .css file suffix from application stylesheet

### PR DESCRIPTION
**Pull request by tysongach**
- It's unneeded and overly verbose
- sass-rails recently deprecated this suffix, https://github.com/rails/sass-rails/commit/d355de9b5aa8b79576c9afcadb58ebe164155861

### CODE REVIEW

**Comment by tute** [comment]
I can't stand all that verbosity! :smile: 

:+1:

**Comment by conchan** [comment]
Fantastic! :shaved_ice:

**Comment by brendastorer** [comment]
Do it! :dancer: :dancer: :dancer:

**Comment by joshuaogle** [comment]
:rocket:

**Pull request merged**
