### PR TITLE
All used ENV variables with sample value in `.sample.env`

### PR DESCRIPTION
**Pull request by Dorian**
Easier discovery of ENV variables

### CODE REVIEW

**Comment by tute** [comment]
I wouldn't add variables with sensible defaults which are not so eager to change:

* `DB_POOL`
* `ASSETS_VERSION`
* `DB_REAPING_FREQUENCY`

Where are the following vars used? I don't think I'd add them.

* `TIMEOUT_IN_SECONDS`
* `WEB_CONCURRENCY`
* `WEB_TIMEOUT`

The change for `SECRET_KEY_BASE` is not necessary.

`SEGMENT_IO_KEY` should read `SEGMENT_KEY`.

I would leave `SMTP_*` empty, or commented out, so we force real values. See related discussion in https://github.com/thoughtbot/suspenders/pull/532#issuecomment-86976291.

Thanks for your work!

**Comment by tute** [comment]
ping @Dorian

**Comment by Dorian** [comment]
Variables were outdated because I used an older version of suspenders.

> I would leave SMTP_* empty, or commented out, so we force real values. See related discussion in
> #532 

Maybe there is a nicer way to introduce the `SMTP_*` than by throwing an exception when deploying on a production env :smile:, but I understand.

(agree on the rest)
(Understood `ASSETS_VERSION` with #220 (interesting))

Thanks for your work, learned a lot from suspenders.

**Comment by tute** [comment]
I'm glad it's useful for you, thanks for your input!

**Pull request closed without merging**
