### PR TITLE
Rails 6.1.1

### LINKED ISSUE #1060: Update for Rails 6.1.0
Suspenders currently locks rails to `~> 6.0.0` on the latest version. It would be nice if there was a new version that allowed users of suspenders to update to the latest version of Rails.

### PR DESCRIPTION
**Pull request by mike-burns**
Along the way some tiny changes were made:

- Use [`config.i18n.raise_on_missing_translations`] instead of the
deprecated setting.
- Unify asset host config under `config.asset_host`.
- Better print-debugging in the test suite for the `destroy` task.

[`config.i18n.raise_on_missing_translations`]: https://github.com/rails/rails/pull/31571

Closes #1060 .

### CODE REVIEW

**Comment by mike-burns** [comment]
I'm not convinced the build failures are related to anything I did. What's the status of CI?

**Comment by mike-burns** [comment]
Some of these tests are failing because [the `gem` command](https://github.com/rails/rails/blob/main/railties/lib/rails/generators/actions.rb#L21) is [irreversible](https://github.com/erikhuda/thor/blob/master/lib/thor/actions/file_manipulation.rb#L268).

**Comment by mike-burns** [comment]
That's because of https://github.com/rails/rails/pull/35285, which swapped from Thor [`append_file`](https://rubydoc.info/gems/thor/Thor/Actions#append_to_file-instance_method) (reversible) to Thor [`gsub_file`](https://rubydoc.info/gems/thor/Thor/Actions#gsub_file-instance_method) (irreversible).

**Comment by mike-burns** [comment]
Fixing it in https://github.com/thoughtbot/suspenders/pull/1066.

**Comment by stevepolitodesign** [comment]
We might want to consider closing this now that #1104 has been merged.

**Comment by mike-burns** [comment]
We Rails 7 now, hey!

**Pull request closed without merging**
