### PR TITLE
fixed hash syntax

### PR DESCRIPTION
**Pull request by askl56**

### CODE REVIEW

**Comment by tute** [comment]
Thanks!

**Comment by askl56** [comment]
Hi @tute Why wasn't it merged?

**Comment by tute** [comment]
It was merged in the referenced commit: https://github.com/thoughtbot/suspenders/commit/32b8f5a61417a563c6adf84ffe2e092726bb6343

**Comment by tute** [comment]
I squashed the commits together and reworded a little the commit message, keeping your authorship.

**Comment by askl56** [comment]
Ah ok cool, sorry, brain fart. Thanks man

**Pull request closed without merging**
