### PR TITLE
Call dynamic-readme reusable workflow

### PR DESCRIPTION
**Pull request by stefannibrasil**
We want to have a way to edit our README footer at one place and have the changes from there be propagated to our repos.

By adding this snippet in the README, we call this reusable workflow: https://github.com/thoughtbot/templates/blob/main/.github/workflows/dynamic-readme.yaml that renders and updates the README footer dynamically.

### CODE REVIEW

**Comment by stefannibrasil** [comment]
@stevepolitodesign any tips on how to make CI happy? 👀

**Comment by stevepolitodesign** [comment]
@stefannibrasil I've noticed CI failures on **new** pull requests made against `main` made after I started working on Suspenders `3.0.0`. I think this is because the new branch introduced an updated `ci.yml` script.

For now, how would you feel about making this pull request against `suspenders-3-0-0`, since it's almost ready?

**Comment by stefannibrasil** [comment]
Got it, thanks! Moved the commit to the `suspenders-3-0-0` branch: https://github.com/thoughtbot/suspenders/compare/dynamic-readme-workflow?expand=1

**Comment by stevepolitodesign** [comment]
@stefannibrasil we're at a point where we can reopen this if you still feel it's worth doing 👍

**Comment by stefannibrasil** [comment]
Thanks, Steve! I can't reopen the branch anymore, so I created a new PR: https://github.com/thoughtbot/suspenders/pull/1208

**Pull request closed without merging**
