### PR TITLE
Set puma workers to 1 in .sample.env to play nice with web-console

### PR DESCRIPTION
**Pull request by delphaber**
Should close https://github.com/thoughtbot/suspenders/issues/570

### CODE REVIEW

**Comment by tute** [comment]
Pinging @seanpdoyle and @jferris for their comments on this.

**Comment by jferris** [comment]
I worry about running a multiprocess server in production (which has the possibility of race conditions and state confusion) but only running a single server locally when developing.

**Comment by seanpdoyle** [comment]
I agree with Joe, but I'm torn.

I usually end up setting this to 1 (and used to do the same with unicorn) while profiling with the local version of https://github.com/newrelic/rpm.

Is there a middle ground? 

Could web-console / newrelic be modified to work with multiple processes (that's obviously out of scope for this PR, but is it worth considering?)?

**Comment by tute** [comment]
> I worry about running a multiprocess server in production (which has the possibility of race conditions and state confusion) but only running a single server locally when developing.

Would we ever reach a point in development or test when we hit a race condition, without actively seeking it? It sounds very unlikely to me, in which case this PR doesn't introduce that potential issue.

**Comment by seanpdoyle** [comment]
@tute @jferris also, `WEB_CONCURRENCY=1` and `MAX_WORKERS=1` resolve some performance / usability issues for `ember-cli-rails` projects:

* https://github.com/thoughtbot/ember-cli-rails/issues/94
* https://github.com/thoughtbot/ember-cli-rails/pull/222
* https://github.com/thoughtbot/dome/pull/19

**Comment by tute** [comment]
Will merge this in unless @seanpdoyle or @jferris object.

@delphaber, can you please rebase your commit on top of latest master, and add context of this discussion into the commit message? Thank you! :)

**Comment by delphaber** [comment]
@tute sure thing :)

**Comment by delphaber** [comment]
Done!

**Comment by tute** [comment]
Thank you!

**Pull request merged**
