### PR TITLE
Upgrade sprockets to 4.0.0.beta3

### PR DESCRIPTION
**Pull request by MattMSumner**
Why:

Currently, a newly generated suspenders rails app has deprecation
warnings [per this issue]. This is due to using the `sprockets-es6`
which was not designed to be a lasting solution to transpiling ES6 to
ES5.

[per this issue]: https://github.com/thoughtbot/suspenders/issues/793

This PR:

Removes `sprockets-es6` in favor of updating `sprockets` to 4.0.0.beta3
and adding the `babel-transpiler` gem. This resolves [this issue].

[this issue]: https://github.com/thoughtbot/suspenders/issues/793

### CODE REVIEW

**Comment by MattMSumner** [comment]
Having generated an app, this works for transpiling es6. However, there seems to be an issue with bourbon and sprockets. I'm getting
```
Sprockets::FileNotFound in Posts#index
couldn't find file '...gems/bourbon-5.0.0.beta.6/core/bourbon/settings/_settings.scss'
```

It seems to be an issue with reassigning variables within a function but I'm still investigating.

**Comment by tute** [comment]
@tysongach have you seen an error like this before?

**Comment by tute** [comment]
Maybe @whmii has?

**Comment by whmii** [comment]
@tute I have not. that is the right path though.

**Comment by MattMSumner** [comment]
@whmii I seem to only have a problem with this setting https://github.com/thoughtbot/bourbon/blob/master/core/bourbon/settings/_settings.scss#L34. It looks like an issue being used here https://github.com/thoughtbot/bourbon/blob/master/core/bourbon/library/_modular-scale.scss#L70. It seems to me that these lines suggest this value should be a list https://github.com/thoughtbot/bourbon/blob/master/core/bourbon/library/_modular-scale.scss#L74-L75 not a singular value?

If I comment out this line https://github.com/thoughtbot/bitters/blob/a1a0ca9188d63596a67379fd07ae8053aed0e653/core/_typography.scss#L15 the page loads and everything works.

**Comment by MattMSumner** [comment]
It seems like this also happens on master. I've created an issue to address: https://github.com/thoughtbot/suspenders/issues/797

**Comment by tute** [comment]
@MattMSumner is this error exactly the same as what happens in master? If so, do you think we should merge this as a step in the right direction, and fix the error in another unrelated PR?

**Comment by tute** [comment]
beta4 has been released: https://github.com/rails/sprockets/releases/tag/v4.0.0.beta4

**Comment by MattMSumner** [comment]
I tried out beta4 with no luck. I've also fought with this for too long and am closing in favor of https://github.com/thoughtbot/suspenders/pull/802

**Pull request closed without merging**
