### PR TITLE
Update Neat to 2.0.0.beta.1

### PR DESCRIPTION
**Pull request by whmii**

### CODE REVIEW

**Comment by tute** [comment]
Changes between versions: https://github.com/thoughtbot/neat/blob/neat-2.0.0/CHANGELOG.md.

LGTM for merge.

**Comment by tute** [comment]
If it's ready though, should we do a full release of Neat, and merge this PR when we have the final version? Is there a reason why we prefer to use it during beta?

**Comment by tute** [comment]
@whmii will we wait for the final release of neat to merge this in? What is a likely timeline for that release? Thank you!

**Comment by tute** [comment]
Ping @whmii. What is the timeline in neat? Should we hold off on merging this PR? Should we release neat and merge this PR? Thanks!

**Comment by tute** [comment]
@whmii @tysongach what's the status of suspenders/neat 2.0?

**Comment by whmii** [comment]
@tute I will try to have a cabal this afternoon to discuss when a sensible release time would be. I believe it is likely that If we will chose to add the neat 2.0, weather it is a beta or not, similar to bourbon. especially now that documentation is available.

**Comment by whmii** [comment]
@tute the Neat beta is now relatively stable. A few things may change but they will be almost exclusively additions and bugfixes and not outright *changes* in functionality. This is similar to the current state of Bourbon 5.0 that has been added to suspenders as well. Also, documentation has been added for Neat 2.0 and is available at http://thoughtbot.github.io/neat-docs/2-0-0-beta-1

IMO this is good to merge, beta or not.

**Comment by tute** [comment]
Cool! I'm fine with merging. If it's stable-enough that you think we should release I'd rather do that first, otherwise feel free to rebase and merge.
Thank you!

**Comment by whmii** [comment]
🎉

**Pull request merged**
