### PR TITLE
Segment.io is now Segment

### PR DESCRIPTION
**Pull request by andyw8**

### CODE REVIEW

**Comment by tute** [comment]
Can you please add context in the commit message? Do you have a link from Segment that presents the rename and steps to take? Thanks!

**Comment by andyw8** [comment]
I couldn't actually find an official announcement for the change, it seems to have happened quietly.

[Here's the update to the analytics-ruby gem](
https://github.com/segmentio/analytics-ruby/commit/c55a0ca7c0ae8fcac697358628d4607ffa8468fa).

And the [quickstart guide for analytics.js](https://segment.com/docs/libraries/analytics.js/quickstart/) shows the updated CDN for the JavaScript snippet.

**Comment by tute** [comment]
And here's a rename in one of segment's repos: https://github.com/segmentio/analytics-android/commit/cb853a9438af8cababe8668a5175e0b2b9f458ac.

Change LGTM.

**Comment by tute** [comment]
Thank you!

**Pull request closed without merging**
