### PR TITLE
Use factory_girl_rails in dev:prime

### PR DESCRIPTION
**Pull request by delphaber**
Otherwise factory girl can't find the factories in the right folder

### CODE REVIEW

**Comment by tute** [comment]
On a just generated suspenders app it works for me:

```
% rake dev:prime
tyson-test_development already exists
tyson-test_test already exists
-- enable_extension("plpgsql")
   -> 0.0161s
-- create_table("delayed_jobs", {:force=>:cascade})
   -> 0.0104s
-- add_index("delayed_jobs", ["priority", "run_at"], {:name=>"delayed_jobs_priority", :using=>:btree})
   -> 0.0029s
-- create_table("users", {:force=>:cascade})
   -> 0.0055s
-- initialize_schema_migrations_table()
   -> 0.0025s
-- enable_extension("plpgsql")
   -> 0.0168s
-- create_table("delayed_jobs", {:force=>:cascade})
   -> 0.0246s
-- add_index("delayed_jobs", ["priority", "run_at"], {:name=>"delayed_jobs_priority", :using=>:btree})
   -> 0.0348s
-- create_table("users", {:force=>:cascade})
   -> 0.0052s
-- initialize_schema_migrations_table()
   -> 0.0008s
```

How can I replicate your issue? Thanks!

**Comment by tute** [comment]
ping @delphaber

**Comment by tute** [comment]
Closing, as this doesn't seem like an issue in suspenders. Please reopen if we can see it is. Thanks!

**Comment by delphaber** [comment]
Hi @tute , sorry. Haven't got much time to test in a new empty suspenders app right now :(

**Pull request closed without merging**
