### PR TITLE
Added .byebug_history to gitignore

### PR DESCRIPTION
**Pull request by ivobenedito**
Think it's not worth to have it committed.

byebug_history_screenshot

@mcmire: Updated the description.

### CODE REVIEW

**Comment by mcmire** [comment]
What problem does this solve?

**Comment by ivobenedito** [comment]
Think it's not worth to have it committed.

byebug_history_screenshot

**Comment by mcmire** [comment]
Alright, thanks for that.

I haven't seen this file appear yet, but this makes sense to me. :+1:

**Comment by ivobenedito** [comment]
@mcmire You're welcome! :)

**Comment by tute** [comment]
> I haven't seen this file appear yet

I haven't seen it either yet.

**Comment by ivobenedito** [comment]
Guess it just started being used from >= 8.1.0

screen shot 2016-01-29 at 20 21 05

**Comment by tute** [comment]
I can see this file being created after using `byebug` on any Ruby file. @geoffharcourt, do you think this should belong in the `dotfiles` or in `suspenders`? Thanks!

**Comment by tute** [comment]
I think this belongs in our dotfiles, as it's a global configuration and not project specific. Opened up a PR there: https://github.com/thoughtbot/dotfiles/pull/483. Thanks!

**Pull request closed without merging**
