### PR TITLE
Changed sass-rails to sassc-rails

### PR DESCRIPTION
**Pull request by theabrad**
The Ruby Sass gem will be deprecated by March 26, 2019
http://sass.logdown.com/posts/7081811 so the suggestion is to use the
`sassc` gem. This adds the `sassc-rails` gem to the Gemfile and removes
`sass-rails`.

### CODE REVIEW

**Comment by composerinteralia** [comment]
I tried this out and I am getting:

```rb
Error: File to import not found or unreadable: neat.
        on line 5 of app/assets/stylesheets/application.scss
>> @import "neat";
```

I think we may something like https://github.com/thoughtbot/neat/pull/666 to be released before we can merge this.

**Comment by mike-burns** [comment]
@composerinteralia do you know what the status of this is now?

**Comment by composerinteralia** [comment]
I think we just need to release `neat`. @tysongach any interest in helping me with that this afternoon?

**Comment by tysongach** [comment]
@composerinteralia I just released Neat v3.0.1, which includes your fix from https://github.com/thoughtbot/neat/commit/a092ff79a5f81be5a01328f9daa5e15f97b4a58a. Give that a shot, and let me know if this is resolved.

**Comment by composerinteralia** [comment]
Looks good. Let's merge https://github.com/thoughtbot/suspenders/pull/959 then this

**Pull request merged**
