### PR TITLE
Remove sprocket-es6

### PR DESCRIPTION
**Pull request by MattMSumner**
Why:

sprockets-es6 is causing depreciation issues for Sprockets, and the gem author says that the gem will never reach v1.0.

This PR:

Removes sprockets-es6. We would like to introduce the babel-transpiler gem in the future but it requires sprockets 4. While sprockets 4 has a beta release, this seems to be causing issues with bourbon neat and bitters per https://github.com/thoughtbot/suspenders/issues/797. Until this is resolved I suggest adding ES6 support on a project by project basis.

Resolves: https://github.com/thoughtbot/suspenders/issues/793

### CODE REVIEW

**Comment by tute** [comment]
LGTM Matt. I'd consider using babel-transpiler and a beta release for Sprockets in the short term. I wouldn't add ES6 on a project by project basis, I'd vote for building the best solution we know for ES6 in Rails apps into suspenders (even if it requires beta sprockets).

This looks good to 🚢. Thank you! :)

**Comment by tute** [comment]
> While sprockets 4 has a beta release, this seems to be causing issues with bourbon neat and bitters per #797.

Nevermind my idea, if we can't run on beta. Thanks!

**Comment by tute** [comment]
After https://github.com/thoughtbot/suspenders/pull/796#issuecomment-257061826 I see there is no good solution yet. Read the threads in the opposite order.
This LGTM. Thank you!

**Comment by mike-burns** [comment]
I don't understand why, but I have Suspenders plus this:

```
% bundle | grep sprockets
Using sprockets 3.7.1
Using sprockets-es6 0.9.2
Using sprockets-rails 3.2.0
```

I am able to write ES6 in files with names ending in `.es6`, deploy to Heroku, and see those files be served as JavaScript. I've seen no deprecation warnings or Bourbon issues, too.

Before I add sprockets-es6 back to Suspenders, what should I do to see the issues raised elsewhere?

**Pull request merged**
