### PR TITLE
Use current versions of Bourbon, Neat, and Rails-sass

### PR DESCRIPTION
**Pull request by kylefiedler**
Solves: https://github.com/thoughtbot/suspenders/issues/472

### CODE REVIEW

**Comment by mike-burns** [comment]
Do all three of these always play together perfectly? Will sass-rails ever be "wicked out of date" again?

**Comment by kylefiedler** [comment]
> Do all three of these always play together perfectly?

All current versions do.

> Will sass-rails ever be "wicked out of date" again?

It's possible with another major release of Sass. 

Are you suggesting that I simply bump up the versions for all of these?

**Comment by delphaber** [comment]
`gem "sass-rails", "~> 5.0"` is "hard-coded" in any new rails 4.2 project, like `gem "coffee-rails", "~> 4.1.0"`

**Comment by mike-burns** [comment]
Kyle, yes: bump the versions until we're sure that there will never be an issue again.

**Comment by croaky** [comment]
Looks good.

**Pull request merged**
